#!/bin/sh

REPO="https://github.com/k-hosokawa/pac/releases/download"
VERSION="1.0.0"

PLATFORM=$(uname)
ARCH="x86_64"

PAC_TARBALL="pac_${VERSION}_${PLATFORM}_${ARCH}.tar.gz"
PAC_URL="${REPO}/v${VERSION}/${PAC_TARBALL}"

BIN_DIR="${PREFIX-/usr/local}/bin"
TMP_DIR="/tmp/pac-install"
mkdir -p $BIN_DIR $TMP_DIR

curl -L $PAC_URL -o "${TMP_DIR}/${PAC_TARBALL}"
tar xzvf "${TMP_DIR}/${PAC_TARBALL}" -C "${TMP_DIR}"
install -m 755 "${TMP_DIR}/pac" "${BIN_DIR}/pac"

rm -rf "${TMP_DIR}"
